### ISSUE TITLE
Feature request: Hardware debugging (386+)

### ISSUE THREAD

**Issue by Excentertex** [Baron-von-Riedesel/DOS-debug#15]
I realize this is low-priority and probably not _really_ needed, but it could be fun to implement 386+ hardware debugging. Think debugging ROM code, conditional breakpoints, I/O debugging etc...

**Comment by Baron-von-Riedesel** [comment]
Yes. Actually, for the ring0 variant (DebugR), cmds BP/BC to set/display/clear hw watchpoint 0 was added. I guess I once needed to trap I/O accesses and implemented this - rather rudimentary, currently.

For the standard versions this would surely mean more work, since access to the DRx registers is restricted and some V86 monitors/DPMI hosts won't allow access to those things at all ( DosEmu/WinXP/... )

**Comment by Baron-von-Riedesel** [comment]
Will be added in v2.03.
